### ISSUE TITLE
TwigException: Unable to parse 'include...' since latest update

### ISSUE THREAD

**Issue by Steviant-zz** [frctl/twig#13]
Getting `TwigException: Unable to parse 'include '@page-link' with link'` and similar whenever I try to `include` another template, since the latest round of updates.

Potential answer seems to be [here](https://github.com/kss-node/kss-node/issues/467#issuecomment-406844915), to do with new namespacing rules in twig.js, but I've tried the solutions in that comment thread and can't figure it out.

**Comment by Chapabu** [comment]
Hmm, I've not noticed this and I've been using it. Thanks for letting us know! Unfortunately, there aren't any tests with this adapter, which is how it robably slipped through. I'll be adding some tests over the coming couple of weeks.

Out of interest, in your example what is `link`. I tend to use the full syntax that is also used in the issue you link to, perhaps that's part of the issue?

**Comment by mihkeleidast** [comment]
Seeing this, too.

Usage in twig looks like this:
`{% include '@logo' with { class: 'header__logo', data: data.logo } %}`
and the config for the component looks like this:
```
{
  "context": {
    "data": {
      "logo": "@logo.data",
    }
  }
}
```

**Comment by therealpecus** [comment]
if anyone has a workaround it'd be appreciated while this issue is being worked out. I tried to force twig to use `RobLoach/twig.js#compile`, v. 1.11.1 and all the way back v0.9.5, as suggested in the linked thread but the error persists. 

@kgierke I noticed that commenting the render tag definition (in `/tags/index.js`) solves the `include` problem. It seems twig extend implementation somehow overwrites/deletes the native include tag. I can't go much further than this in troubleshooting, hope it helps.

**Comment by Steviant-zz** [comment]
The `link` variable in that example worked fine with previous versions of the adapter. I've just rolled back to `1.0.0-beta.3` and it works again.

**Comment by therealpecus** [comment]
You can keep `1.0.0-beta.4` and the `render` tag by changing the `type` property of `tags/render.js` to a custom value (e.g. `'rendertag'`). It seems that using the internal twig type `Twig.logic.type.include` overrides the `include` tag.

cc: @kgierke

**Comment by kgierke** [comment]
Yeah the documentation on custom twig functions is not that great, should have tested the include functionality on my render tag implementation. But great that you have found a fix for it already!
